name: Release library

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build-release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'     
          registry-url: 'https://registry.npmjs.org'

      - name: 'Install PNPM'
        uses: pnpm/action-setup@v4
        with:
          version: '9'

      - name: 'Install packages'
        run: pnpm install

      - name: 'Run tests'
        run: pnpm run test

      - name: 'Build library'
        run: pnpm run build

      - name: 'Publish library'
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}